### ISSUE TITLE
continucação

### ISSUE THREAD

**Issue by pauloXavier89** [Eschechola/ARTIGO-AuthenticationJWT#1]
Olá, amigo. Li o seu tutorial e achei muito bom, inclusive estou seguindo ele, mas fiquei com uma dúvida. Depois que tenho o token, faço o que com ele? Se eu quiser criar uma rota de outra entidade validando pelo token, como seria a chamada para a API, onde esse token vai?

**Comment by Eschechola** [comment]
Opa, tudo bem, então após pegar o token você se identificou (autenticou), agora basta enviar esse token no Header da sua requisição Http, adicionando.

Authorization Bearer <Token>

E realizar a requisição, a rota no ASP .NET que deve ter a tag [Authorize] em cima de sua assinatura vai pegar esse token e verificar se você tem permissão de acesso, esse processo acontece automaticamente através do middleware do ASP .NET Core, você só precisa adicionar o [Authorize] nas rotas que deseja proteger.

No caso de ter autenticações específicar você poder usar Roles, por exemplo uma rota comum pode ser acessado por qualquer token, outra rota somente pra quem tem token com Role de administrador.

Pra isso você precisa colocar a tag [Authorize(Role="Admin")], e na hora de gerar o token informar qual role a dele.
